ASSUME CS: CODE
CODE SEGMENT
START:  MOV AX,2000H
        MOV DS,AX
        MOV AX,4000H
        MOV ES,AX
        MOV SI, 2000H
        MOV DI,2008H
        MOV CX, 0008H
        CLD
        REPZ MOV SB
        INT 21H
CODE ENDS
END START