ASSUME CS: CODE
CODE SEGMENT
START: MOV AX,2100H
      MOV DS,AX
      MOV SI, 1000H
      MOV DI, 2000H
      MOV BX,0004
      MOV CL, 04H
      ADD DI, BX
UP: MOV AL,[SI]
    ROR AL,CL
    MOV [DI], AL
    DEC DI
    INC SI
    DEC BX
    JNZ UP
    INT 21H
CODE ENDS
END START